version: '3.7'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    volumes:
      - static_volume:/code/static
      - media_volume:/media
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.5-alpine
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/code/static
      - media_volume:/media
    restart: unless-stopped

  dockerhub:
    build: .
    image: gooncharova2/foodgram:v20.01.2021

volumes:
  postgres_data:
  static_volume:
  media_volume: