# Generated by Django 3.0.8 on 2020-12-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20201204_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount',
            old_name='unit',
            new_name='amount',
        ),
    ]
