# Generated by Django 3.0.8 on 2020-12-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20201211_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='checkbox_style',
        ),
    ]
