# Generated by Django 3.0.8 on 2020-12-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20201211_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='checkbox_style',
            field=models.CharField(default='default_style', max_length=100),
            preserve_default=False,
        ),
    ]
