# Generated by Django 3.0.8 on 2020-12-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20201215_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='recipe',
            new_name='recipe_fav',
        ),
    ]
