# Generated by Django 3.0.8 on 2020-12-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20201215_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='recipe_fav',
            new_name='recipe',
        ),
    ]
