# Generated by Django 3.0.8 on 2020-12-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20201222_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2020-12-22 19:26', verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
