# Generated by Django 3.0.8 on 2020-12-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_auto_20201222_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag', to='recipes.Tag', verbose_name='Тег'),
        ),
    ]
