# Generated by Django 3.0.8 on 2020-12-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_auto_20201224_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag', to='recipes.Tag', verbose_name='Тег'),
        ),
    ]
