# Generated by Django 3.0.8 on 2020-12-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_auto_20201224_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
