# Generated by Django 3.0.8 on 2020-12-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0030_auto_20201224_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tags',
            new_name='tag',
        ),
    ]
