# Generated by Django 3.0.8 on 2020-12-29 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0034_auto_20201224_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_amount', to='recipes.Recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients_recipe', through='recipes.Amount', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
